[package]
name = "payments-engine"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
csv = "1.4.0"
rust_decimal = { version = "1.42.1", default-features = false, features = ["std"] }
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
tempfile = "3.27.0"
